# Generated by Django 5.1.7 on 2025-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textmodel', models.TextField()),
                ('checks', models.BooleanField(default=False)),
            ],
        ),
    ]
