# Generated by Django 5.1.7 on 2025-03-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textstore',
            name='checks',
        ),
    ]
