# Generated by Django 5.1.7 on 2025-03-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_textstore_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='textstore',
            name='isdelete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
