# Generated by Django 5.1.7 on 2025-03-31 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_textstore_isdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='textstore',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='textstore',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
